name: jsAction

discrption: A JavaScript action that runs a simple console log to calculate

inputs:
  number1:
    required: true
    default: 0
  numher2:
    required: true
    default: 0
outputs:
  result:
   description: 'The result of the calculation'
runs:
 using: 'node20'
 main: 'dist/index.js'