name: jsAction

on:
  push:
jobs:
  test-js-action:
    name: Test JavaScript Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: jsAction
        with:
          number1: 2
          number2: 2
      - run: echo ${{ steps.jsAction.outputs.result }}
  